# Generated by Django 4.2 on 2024-03-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='chat_bot_name',
            field=models.CharField(default='مر', max_length=5),
        ),
    ]
