# Generated by Django 4.2 on 2024-03-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userprofile_chat_bot_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='chat_bot_name',
            field=models.CharField(default='مریم', max_length=5),
        ),
    ]
