# Generated by Django 4.2 on 2024-03-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_chat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ai_mode',
            field=models.BooleanField(default=True),
        ),
    ]
