# Generated by Django 4.2 on 2024-03-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_ai_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='ai_mode',
        ),
        migrations.AddField(
            model_name='chat',
            name='ai_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='message',
            name='From',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
