# Generated by Django 4.2 on 2024-03-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_message_ai_mode_chat_ai_mode_message_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='author',
            new_name='User',
        ),
    ]
