# Generated by Django 4.2 on 2024-03-25 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_author_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='User',
        ),
    ]
