# Generated by Django 4.2 on 2024-03-25 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chat_customer_alter_message_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='dealer_name',
            new_name='dealer',
        ),
    ]
