# Generated by Django 4.2 on 2024-03-25 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customers_gender'),
        ('chat', '0008_rename_dealer_name_chat_dealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customers'),
        ),
    ]
