# Generated by Django 4.2 on 2024-03-25 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customers_gender'),
        ('chat', '0009_alter_chat_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='From',
        ),
        migrations.AddField(
            model_name='message',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customers'),
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(blank=True, choices=[('Customer', 'C'), ('AI', 'A'), ('Dealer', 'D')], max_length=25),
        ),
    ]
