# Generated by Django 4.2 on 2024-03-26 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_remove_message_from_message_customer_message_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='type',
            new_name='message_type',
        ),
    ]
