# Generated by Django 4.2 on 2024-03-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_rename_type_message_message_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat_name',
        ),
    ]
