# Generated by Django 4.2 on 2024-03-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customers_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F')], default='M', max_length=10),
        ),
    ]
